# Generated by Django 5.0.4 on 2024-04-23 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploaded_images/')),
                ('prediction', models.CharField(blank=True, max_length=10)),
                ('confidence', models.FloatField(blank=True, default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='SimilarImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_instances', to='myapp.images')),
                ('similar_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to', to='myapp.images')),
            ],
        ),
    ]
